export const ACCESS_TOKEN = "ACCESS_TOKEN";
export const SALES_ACCESS_TOKEN = "SALES_ACCESS_TOKEN";
export const RESETPASSWORD = "RESETPASSWORD";
//export const ACCESS_TOKEN_ADMIN = 'ACCESS_TOKEN_ADMIN';
export const CLIENT_ACCESS_TOKEN = 'CLIENT_ACCESS_TOKEN';
export const ADMIN_ACCESS_TOKEN = "ADMIN_ACCESS_TOKEN";
export const PROJECT_MANAGER_ACCESS_TOKEN = "PROJECT_MANAGER_ACCESS_TOKEN";
export const REQUEST_LOAD_USER_DATA = "REQUEST_LOAD_USER_DATA";
export const RECEIVE_LOAD_USER_DATA = "RECEIVE_LOAD_USER_DATA";
export const GUEST_LOGIN = "GUEST_LOGIN";
export const GUEST_LOGIN_RESPONSE = "GUEST_LOGIN_RESPONSE";
export const RECEIVE_LOAD_DISTRICT_DATA = "RECEIVE_LOAD_DISTRICT_DATA";
export const VERIFY_OTP_RESPONSE = "VERIFY_OTP_RESPONSE";
export const VERIFY_OTP = "VERIFY_OTP";
export const VALIDATE_OTP_DATE = "VALIDATE_OTP_DATE";
export const METAL_TYPE_DATE = "METAL_TYPE_DATE";
export const ADD_INVITEE_DATA = "ADD_INVITEE_DATA";
export const ADD_INVITEE_RESPONSE = "ADD_INVITEE_RESPONSE";
export const RECEIVE_LOAD_OTP_DATA = "RECEIVE_LOAD_OTP_DATA";
export const CALL_CENTER_LOGIN_PAGE_DATA = "CALL_CENTER_LOGIN_PAGE_DATA";
export const CALL_CENTER_LOGIN_PAGE_RESPONSE =
  "CALL_CENTER_LOGIN_PAGE_RESPONSE";
export const VERIFY_CREDENTIAL = "VERIFY_CREDENTIAL";
export const REQUEST_ALL_USERS = "REQUEST_ALL_USERS";
export const ALL_USERS_RESPONSE = "ALL_USERS_RESPONSE";
export const ADD_USER = "ADD_USER";
export const ADD_USER_RESPONSE = "ADD_USER_RESPONSE";
export const REQUEST_LOAD_TIMEZONE_LIST_DATA =
  "REQUEST_LOAD_TIMEZONE_LIST_DATA";
export const RECEIVE_LOAD_TIMEZONE_LIST_DATA =
  "RECEIVE_LOAD_TIMEZONE_LIST_DATA";
export const REQUEST_LOAD_TIMESLOT_LIST_DATA =
  "REQUEST_LOAD_TIMESLOT_LIST_DATA";
export const RECEIVE_LOAD_TIMESLOT_LIST_DATA =
  "RECEIVE_LOAD_TIMESLOT_LIST_DATA";
export const REQUEST_DEMO = "REQUEST_DEMO";
export const RECEIVE_DEMO = "RECEIVE_DEMO";
export const REQUEST_ALL_SHOWROOMS = "REQUEST_ALL_SHOWROOMS";
export const ALL_SHOWROOMS_RESPONSE = "ALL_SHOWROOMS_RESPONSE";
export const DELETE_SHOWROOM = "DELETE_SHOWROOM";
export const DELETE_SHOWROOM_RESPONSE = "DELETE_SHOWROOM_RESPONSE";
export const ADD_SHOWROOM = "ADD_SHOWROOM";
export const ADD_SHOWROOM_RESPONSE = "ADD_SHOWROOM_RESPONSE";
export const LOGIN_PAGE_DATA = "LOGIN_PAGE_DATA";
export const LOGIN_PAGE_RESPONSE = "LOGIN_PAGE_RESPONSE";
export const VERIFY_LOGIN = "VERIFY_LOGIN";

export const VERIFY_OTP_LOGIN = "VERIFY_OTP_LOGIN";
export const RESPONCES_OTP_LOGIN = "RESPONCES_OTP_LOGIN ";

export const REQUEST_ALL_TICKETS = "REQUEST_ALL_TICKETS";
export const ALL_TICKETS_RESPONSE = "ALL_TICKETS_RESPONSE";
/*User management screens changes*/
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_RESPONSE = "DELETE_USER_RESPONSE";
/*showroom management screens changes*/
export const DELETE_PLACE = "DELETE_PLACE";
export const DELETE_PLACE_RESPONSE = "DELETE_PLACE_RESPONSE";
export const DELETE_PLACES = "DELETE_PLACE";
export const DELETE_PLACES_RESPONSE = "DELETE_PLACE_RESPONSE";
export const ALL_REPORTS_RESPONSE = "ALL_REPORTS_RESPONSE";
export const REQUEST_ALL_REPORTS = "REQUEST_ALL_REPORTS";

/*These are user requests constants */
export const REQ_LOAD_REQUEST_DATA = "REQ_LOAD_REQUEST_DATA";
export const REC_LOAD_REQUEST_DATA = "REC_LOAD_REQUEST_DATA";
export const REQ_LOAD_SHOWROOM_DATA = "REQ_LOAD_SHOWROOM_DATA";
export const REC_LOAD_SHOWROOM_DATA = "REC_LOAD_SHOWROOM_DATA";
export const REQ_LOAD_SALESPERSON_LIST_DATA = "REQ_LOAD_SALESPERSON_LIST_DATA";
export const REC_LOAD_SALESPERSON_LIST_DATA = "REC_LOAD_SALESPERSON_LIST_DATA";
export const REQ_LOAD_ITASSIGNEE_LIST_DATA = "REQ_LOAD_ITASSIGNEE_LIST_DATA";
export const REC_LOAD_ITASSIGNEE_LIST_DATA = "REC_LOAD_ITASSIGNEE_LIST_DATA";
export const REQ_LOAD_SALESPERSON_BY_SHOWROOM =
  "REQ_LOAD_SALESPERSON_BY_SHOWROOM";
export const REC_LOAD_SALESPERSON_BY_SHOWROOM =
  "REC_LOAD_SALESPERSON_BY_SHOWROOM";
export const REQ_SAVE_ASSIGN_REQUEST = "REQ_SAVE_ASSIGN_REQUEST";
export const REC_SAVE_ASSIGN_REQUEST = "REC_SAVE_ASSIGN_REQUEST";
export const REQ_SAVE_REASSIGN_REQUEST = "REQ_SAVE_REASSIGN_REQUEST";
export const REC_SAVE_REASSIGN_REQUEST = "REC_SAVE_REASSIGN_REQUEST";
export const REQ_AVAILABLE_SLOTS = "REQ_AVAILABLE_SLOTS";
export const REC_AVAILABLE_SLOTS = "REC_AVAILABLE_SLOTS";
export const REQ_SAVE_RESCHEDULE_REQUEST = "REQ_SAVE_RESCHEDULE_REQUEST";
export const REC_SAVE_RESCHEDULE_REQUEST = "REC_SAVE_RESCHEDULE_REQUEST";
export const REQ_CANCELLATION_REQUEST = "REQ_CANCELLATION_REQUEST";
export const REC_CANCELLATION_REQUEST = "REC_CANCELLATION_REQUEST";
export const REQ_COMPLETION_REQUEST = "REQ_COMPLETION_REQUEST";
export const REC_COMPLETION_REQUEST = "REC_COMPLETION_REQUEST";

export const MODE_ASSIGN = "ASSIGN";
export const MODE_REASSIGN = "REASSIGN";
export const REQUEST_LOAD_BRANCH_LIST_DATA = "REQUEST_LOAD_BRANCH_LIST_DATA";
export const RECEIVE_LOAD_BRANCH_LIST_DATA = "RECEIVE_LOAD_BRANCH_LIST_DATA";
export const REQUEST_LOAD_PRIMARY_LIST_DATA = "REQUEST_LOAD_PRIMARY_LIST_DATA";
export const RECEIVE_LOAD_PRIMARY_LIST_DATA = "RECEIVE_LOAD_PRIMARY_LIST_DATA";

export const DATE_DATA = "REQUEST_ALL_TICKETS";
export const DATA_RESPONSE = "ALL_TICKETS_RESPONSE";
export const RECEIVE_SLOT_DATA = "RECEIVE_SLOT_DATA";
export const METAL_DATA = "METAL_DATA";
export const METAL_RESPONSE = "METAL_DATA_RESPONSE";
export const RESPONSE_METAL = "RESPONSE_METAL";

export const FORGOTPASSWORD_DATA = "FORGOTPASSWORD_DATA";
export const FORGOTPASSWORD_RESPONSE = "FORGOTPASSWORD_RESPONSE";
export const RECEIVE_FORGOTPASSWORD = "RECEIVE_FORGOTPASSWORD";
export const ADD_FEEDBACK = "ADD_FEEDBACK";
export const ADD_FEEDBACK_RESPONSE = "ADD_FEEDBACK_RESPONSE";

export const FORGOTPASSWORD_VERIFY_OTP_RESPONSE =
  "FORGOTPASSWOR_VERIFY_OTP_RESPONSE";
export const FORGOTPASSWORD_VERIFY_OTP = "FORGOTPASSWOR_VERIFY_OTP";

export const RESETPASSWORD_DATA = "RESETPASSWORD_DATA";
export const RESETPASSWORD_RESPONCES = "RESETPASSWORD_RESPONCES";
export const REQUEST_ALL_DETAILS = "REQUEST_ALL_DETAILS";
export const ALL_DETAILS_RESPONSE = "ALL_DETAILS_RESPONSE";

export const CONTRACT_UPDATE = "CONTRACT_UPDATE";
export const CONTRACT_UPDATE_RESPONSE = "CONTRACT_UPDATE_RESPONSE";

export const CONTRACT_TERMINATE = "CONTRACT_TERMINATE";
export const CONTRACT_TERMINATE_RESPONSE = "CONTRACT_TERMINATE_RESPONSE";

export const REQ_CLEAR_ACCESS_TOKENS = "REQ_CLEAR_ACCESS_TOKENS";
export const REC_CLEAR_ACCESS_TOKENS = "REC_CLEAR_ACCESS_TOKENS";

export const REQUEST_LOAD_CITY_LIST_DATA_REG =
  "REQUEST_LOAD_CITY_LIST_DATA_REG";
export const RECEIVE_LOAD_CITY_LIST_DATA_REG =
  "RECEIVE_LOAD_CITY_LIST_DATA_REG";

export const REQUEST_LOAD_CITY_LIST_DATA = "REQUEST_LOAD_CITY_LIST_DATA";
export const RECEIVE_LOAD_CITY_LIST_DATA = "RECEIVE_LOAD_CITY_LIST_DATA";
export const REQUEST_LOAD_CITY_DATA = "REQUEST_LOAD_CITY_DATA";
export const RECEIVE_LOAD_CITY_DATA = "RECEIVE_LOAD_CITY_DATA";
export const LOGIN_RESENDOTP_VERIFY = "LOGIN_RESENDOTP_VERIFY";
export const LOGIN_RESENDOTP_RESPONSE = "LOGIN_RESENDOTP_RESPONSE";

export const LOGIN_RESEND_OTP_VERIFY = "LOGIN_RESEND_OTP_VERIFY";
export const LOGIN_RESEND_OTP_RESPONSE = "LOGIN_RESEND_OTP_RESPONSE";

export const GUEST_RESENDOTP_VERIFY = "GUEST_RESENDOTP_VERIFY";
export const GUEST_RESENDOTP_RESPONSE = "GUEST_RESENDOTP_RESPONSE";

export const GUEST_RESENDOTP_REGISTER_VERIFY =
  "GUEST_RESENDOTP_REGISTER_VERIFY";
export const GUEST_RESENDOTP_REGISTER_RESPONSE =
  "GUEST_RESENDOTP_REGISTER_RESPONSE";
export const VERIFY_OTP_REGISTER_RESPONSE = "VERIFY_OTP_REGISTER_RESPONSE";
export const VERIFY_OTP_REGISTER = "VERIFY_OTP_REGISTER";
export const CUSTOMER_VERIFY_OTP_REGISTER_RESPONSE =
  "CUSTOMER_VERIFY_OTP_REGISTER_RESPONSE";
export const CUSTOMER_VERIFY_OTP_REGISTER = "CUSTOMER_VERIFY_OTP_REGISTER";
export const REGISTER_PASSWORD_DATA = ".REGISTER_PASSWORD_DATA";
export const REGISTER_PASSWORD_RESPONCES = "REGISTER_PASSWORD_RESPONCES";
export const CUSTOMER_LOGIN_PAGE_RESPONSE = "CUSTOMER_LOGIN_PAGE_RESPONSE";
export const VERIFY_CUSTOMER_LOGIN_CREDENTIAL =
  "VERIFY_CUSTOMER_LOGIN_CREDENTIAL";

export const FORGOTPASSWORD_CUSTOMER_DATA = "FORGOTPASSWORD_CUSTOMER_DATA";
export const FORGOTPASSWORD_CUSTOMER_RESPONSE =
  "FORGOTPASSWORD_CUSTOMER_RESPONSE";
export const FORGOTPASSWORD_CUSTOMER_VERIFY_OTP_RESPONSE =
  "FORGOTPASSWOR_CUSTOMER_VERIFY_OTP_RESPONSE";
export const FORGOTPASSWORD_CUSTOMER_VERIFY_OTP =
  "FORGOTPASSWOR_CUSTOMER_VERIFY_OTP";
export const VALIDATE_OTP_CUSTOMER_DATE = "VALIDATE_OTP_CUSTOMER_DATE";
export const LOGIN_RESENDOTP_CUSTOMER_VERIFY =
  "LOGIN_RESENDOTP_CUSTOMER_VERIFY";
export const LOGIN_RESENDOTP_CUSTOMER_RESPONSE =
  "LOGIN_RESENDOTP_CUSTOMER_RESPONSE";
export const RESETPASSWORD_CUSTOMER_DATA = "RESETPASSWORD_CUSTOMER_DATA";
export const RESETPASSWORD_CUSTOMER_RESPONCES =
  "RESETPASSWORD_CUSTOMER_RESPONCES";

export const REQUEST_LOAD_COMPANY_LIST_DATA = "REQUEST_LOAD_COMPANY_LIST_DATA";
export const RECEIVE_LOAD_COMPANY_LIST_DATA = "RECEIVE_LOAD_COMPANY_LIST_DATA";

export const REQUEST_LOAD_COMPANY_ID = "REQUEST_LOAD_COMPANY_ID";
export const RECEIVE_LOAD_COMPANY_ID = "RECEIVE_LOAD_COMPANY_ID";

export const ADD_TAXS = "ADD_TAXS";
export const ADD_TAXS_RESPONSE = "ADD_TAXS_RESPONSE";
export const ADD_CLIENT = "ADD_CLIENT";
export const ADD_CLIENT_RESPONSE = "ADD_CLIENT_RESPONSE";

export const REQUEST_ALL_TAX = "REQUEST_ALL_TAX";
export const ALL_TAX_RESPONSE = "ALL_TAX_RESPONSE";
export const REQUEST_ALL_PRICE = "REQUEST_ALL_PRICE";
export const ALL_PRICE_RESPONSE = "ALL_PRICE_RESPONSE";

export const REQUEST_ALL_CLIENTS = "REQUEST_ALL_CLIENTS";
export const ALL_CLIENTS_RESPONSE = "ALL_CLIENTS_RESPONSE";


export const DELETE_TAXS = "DELETE_TAXS";
export const DELETE_TAXS_RESPONSE = "DELETE_TAXS_RESPONSE";
export const DELETE_TAXS_RESPONSE_BY_COUNTRY = "DELETE_TAXS_RESPONSE_BY_COUNTRY";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const DELETE_CLIENT_RESPONSE = "DELETE_CLIENT_RESPONSE";

export const REQUEST_CALCULATE_PRICE = "REQUEST_CALCULATE_PRICE";
export const RECEIVE_CALCULATE_PRICE = "RECEIVE_CALCULATE_PRICE";
export const REQUEST_LITE_CALCULATE_PRICE = "REQUEST_LITE_CALCULATE_PRICE";
export const RECEIVE_LITE_CALCULATE_PRICE = "RECEIVE_LITE_CALCULATE_PRICE";
export const REQUEST_LITE_TIME = "REQUEST_LITE_TIME";
export const RECEIVE_LITE_TIME = "RECEIVE_LITE_TIME";

export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const PROFILE_UPDATE_RESPONSE = "PROFILE_UPDATE_RESPONSE";

export const REQUEST_LOAD_UPDATE_USER_LIST_DATA =
  "REQUEST_LOAD_UPDATE_USER_LIST_DATA";
export const RECEIVE_LOAD_UPDATE_USER_LIST_DATA =
  "RECEIVE_LOAD_UPDATE_USER_LIST_DATA";

export const REQUEST_ENTERPRISE_CALCULATE_PRICE =
  "REQUEST_ENTERPRISE_CALCULATE_PRICE";
export const RECEIVE_ENTERPRISE_CALCULATE_PRICE =
  "RECEIVE_ENTERPRISE_CALCULATE_PRICE";
export const REQUEST_PREMIUM_CALCULATE_PRICE =
  "REQUEST_PREMIUM_CALCULATE_PRICE";
export const RECEIVE_PREMIUM_CALCULATE_PRICE =
  "RECEIVE_PREMIUM_CALCULATE_PRICE";

export const REQ_CLEAR_ACCESS_TOKENS_CUSTOMER =
  "REQ_CLEAR_ACCESS_TOKENS_CUSTOMER";
export const REC_CLEAR_ACCESS_TOKENS_CUSTOMER =
  "REC_CLEAR_ACCESS_TOKENS_CUSTOMER";

export const REQUEST_FINAL_CALCULATE_PRICE = "REQUEST_FINAL_CALCULATE_PRICE";
export const RECEIVE_FINAL_CALCULATE_PRICE = "RECEIVE_FINAL_CALCULATE_PRICE";

export const REQUEST_CHECKSTATUS = "REQUEST_CHECKSTATUS";
export const RECEIVE_CHECKSTATUS = "RECEIVE_CHECKSTATUS";

export const GET_PRICE_DETAILS = "GET_PRICE_DETAILS";
export const GET_PRICE_DETAILS_RESPONSE = "GET_PRICE_DETAILS_RESPONSE";

export const CUSTOMIZE_GET_PRICE_DETAILS = "CUSTOMIZE_GET_PRICE_DETAILS";
export const CUSTOMIZE_GET_PRICE_DETAILS_RESPONSE =
  "CUSTOMIZE_GET_PRICE_DETAILS_RESPONSE";

export const CUSTOMIZE_REQUEST_FINAL_CALCULATE_PRICE =
  "CUSTOMIZE_REQUEST_FINAL_CALCULATE_PRICE";
export const CUSTOMIZE_RECEIVE_FINAL_CALCULATE_PRICE =
  "CUSTOMIZE_RECEIVE_FINAL_CALCULATE_PRICE";

export const UPDATE_AGREEMENT = "UPDATE_AGREEMENT";
export const RESPONCES_UPDATE_AGREEMENT = "RESPONCES_UPDATE_AGREEMENT";

export const INSERT_PLAN = "INSERT_PLAN";
export const RESPONCES_INSERT_PLAN = "RESPONCES_INSERT_PLAN";

export const GET_PRICE_BY_TERMS = "GET_PRICE_BY_TERMS";
export const GET_PRICE_BY_TERMS_RESPONSE = "GET_PRICE_BY_TERMS_RESPONSE";

export const CUSTOMEIZE_PAGE_2_DATA = "CUSTOMEIZE_PAGE_2_DATA";

export const CUSTOMEIZE_PAGE_1_DATA = "CUSTOMEIZE_PAGE_1_DATA";

export const REQUEST_INR = "REQUEST_INR";
export const RESPONSE_INR = "RESPONSE_INR";

export const ACCESS_EMAIL = "ACCESS_EMAIL";
export const ACCESS_EMAIL_ID = "ACCESS_EMAIL_ID";
export const REGISTERED = "REGISTERED";
export const PLAN_DETAILS = "PLAN_DETAILS";

export const REQUEST_FILE_UPLOAD = "REQUEST_FILE_UPLOAD";
export const RESPONSE_FILE_UPLOAD = "RESPONSE_FILE_UPLOAD";

export const REQUEST_LOAD_CUSTOMERID_LIST = "REQUEST_LOAD_CUSTOMERID_LIST";
export const RECEIVE_LOAD_COSTOMERID_LIST = "RECEIVE_LOAD_CUSTOMERID_LIST";
export const REQUEST_LOAD_VIEW_INVOICE_LIST = "REQUEST_LOAD_VIEW_INVOICE_LIST";
export const RECEIVE_LOAD_VIEW_INVOICE_LIST = "RECEIVE_LOAD_VIEW_INVOICE_LIST";
export const ACCESS_CUSTOMERID = "ACCESS_CUSTOMERID";
export const CURRENCY_CODE = "CURRENCY_CODE";
export const ACCESS_INVOICENUMB = "ACCESS_INVOICENUMB";
export const ACCESS_COUNTRY = "ACCESS_COUNTRY";
export const ACCESS_INVOICEDATE = "ACCESS_INVOICEDATE";
export const ACCESS_PAYMENTTERMS = "ACCESS_PAYMENTTERMS";
export const ACCESS_DUEDATE = "ACCESS_DUEDATE";
export const ACCESS_ITEM = "ACCESS_ITEM";
export const ACCESS_SUBTOTAL = "ACCESS_SUBTOTAL";
export const ACCESS_TOTAL = "ACCESS_TOTAL";
export const ACCESS_BALANCEDUE = "ACCESS_BALANCEDUE";
export const ACCESS_TOTALINWORDS = "ACCESS_TOTALINWORDS";
export const ACCESS_ADDRESS = "ACCESS_ADDRESS";
export const ACCESS_CITY = "ACCESS_CITY";
export const ACCESS_COMPANY = "ACCESS_COMPANY";
export const ACCESS_PINCODE = "ACCESS_PINCODE";
export const ACCESS_INVOICETOKEN = "ACCESS_INVOICETOKEN";
export const ACTIVE_PLAN = "ACTIVE_PLAN";

export const REQUEST_DMSA_ANNEXURE = "REQUEST_DMSA_ANNEXURE";
export const RECEIVE_DMSA_ANNEXURE = "RECEIVE_DMSA_ANNEXURE";

export const VALIDATE_INVOICE = "VALIDATE_INVOICE";
export const REQUEST_INVOICE_OTP = "REQUEST_INVOICE_OTP";
export const RESPONSE_OTP = "RESPONSE_OTP";
export const RESEND_WAIVEOFF_CODE = "RESEND_WAIVEOFF_CODE";
export const REQUEST_ALL_DETAILS_INVOICE = ".REQUEST_ALL_DETAILS_INVOICE";
export const ALL_DETAILS_INVOICE_RESPONSE = "ALL_DETAILS_INVOICE_RESPONSE";
export const DOWNLOAD_INVOICE = "DOWNLOAD_INVOICE";
export const RECEIVE_DOWNLOAD_INVOICE = "RECEIVE_DOWNLOAD_INVOICE";
export const REQUEST_LOAD_CHOOSEPLANS_LIST = "REQUEST_LOAD_CHOOSEPLANS_LIST";
export const RECEIVE_LOAD_CHOOSEPLANS_LIST = "RECEIVE_LOAD_CHOOSEPLANS_LIST";
export const REQUEST_INVOICE_NUMBER = "REQUEST_INVOICE_NUMBER";
export const RESPONSE_INVOICE = "RESPONSE_INVOICE";
export const RESEND_WAIVEOFF_CODE_RESPONSE = "RESEND_WAIVEOFF_CODE_RESPONSE";
export const REQUEST_CONTACT_US = "REQUEST_CONTACT_US";
export const RESPONSE_CONTACT_US = "RESPONSE_CONTACT_US";

export const DELETE_INVOICE = "DELETE_INVOICE";
export const DELETE_INVOICE_RESPONSE = "DELETE_INVOICE_RESPONSE";

export const CREATE_INVOICES_PAYMENT_REQUEST =
  "CREATE_INVOICES_PAYMENT_REQUEST";
export const CREATE_INVOICES_PAYMENT_RESPONCES =
  "CREATE_INVOICES_PAYMENT_RESPONCES";

export const DMSA_CREATE_INVOICES_PAYMENT_REQUEST =
  "DMSA_CREATE_INVOICES_PAYMENT_REQUEST";
export const DMSA_CREATE_INVOICES_PAYMENT_RESPONCES =
  "DMSA_CREATE_INVOICES_PAYMENT_RESPONCES";

export const TAX_INVOICES_PAYMENT_REQUEST = "TAX_INVOICES_PAYMENT_REQUEST";
export const TAX_INVOICES_PAYMENT_RESPONCES = "TAX_INVOICES_PAYMENT_RESPONCES";

export const INVOICES_PAYMENT_REQUEST = "INVOICES_PAYMENT_REQUEST";
export const INVOICES_PAYMENT_RESPONCES = "INVOICES_PAYMENT_RESPONCES";

export const CUSTOMIZE_REQUEST_LOAD_TIMEZONE_LIST_DATA =
  "CUSTOMIZE_REQUEST_LOAD_TIMEZONE_LIST_DATA";
export const CUSTOMIZE_RECEIVE_LOAD_TIMEZONE_LIST_DATA =
  "CUSTOMIZE_RECEIVE_LOAD_TIMEZONE_LIST_DATA";

export const UPGRADE_REQUEST_LOAD_TIMEZONE_LIST_DATA =
  "UPGRADE_REQUEST_LOAD_TIMEZONE_LIST_DATA";
export const UPGRADE_RECEIVE_LOAD_TIMEZONE_LIST_DATA =
  "UPGRADE_RECEIVE_LOAD_TIMEZONE_LIST_DATA";

export const REQUEST_AUTOMATED_TIME = "REQUEST_AUTOMATED_TIME";
export const RECEIVE_LITE_AUTOMATED_TIME = "RECEIVE_LITE_AUTOMATED_TIME";

export const REQUEST_AUTOMATED_TIME_ENTERPRISE =
  "REQUEST_AUTOMATED_TIME_ENTERPRISE";
export const RECEIVE_ENTERPRISE_AUTOMATED_TIME =
  "RECEIVE_ENTERPRISE_AUTOMATED_TIME";

export const REQUEST_AUTOMATED_TIME_PREMIUM = "REQUEST_AUTOMATED_TIME_PREMIUM";
export const RECEIVE_PREMIUM_AUTOMATED_TIME = "RECEIVE_PREMIUM_AUTOMATED_TIME";

export const EDIT_PROFILE_UPDATE = "EDIT_PROFILE_UPDATE";
export const EDIT_PROFILE_UPDATE_RESPONSE = "EDIT_PROFILE_UPDATE_RESPONSE";

export const EDIT_RESEND_OTP = "EDIT_RESEND_OTP";
export const EDIT_RESEND_OTP_RESPONSE = "EDIT_RESEND_OTP_RESPONSE";

export const CREATE_ORDER_ID = "CREATE_ORDER_ID";
export const RESPONSE_CREATE_ORDER_ID = "RESPONSE_CREATE_ORDER_ID";

export const CREATE_ORDER_ID_TER = "CREATE_ORDER_ID_TER";
export const RESPONSE_CREATE_ORDER_ID_TER = "RESPONSE_CREATE_ORDER_ID_TER";

export const REQUEST_LOAD_DETAILS_LIST_DATA = "REQUEST_LOAD_DETAILS_LIST_DATA";
export const RECEIVE_LOAD_DETAILS_LIST_DATA = "RECEIVE_LOAD_DETAILS_LIST_DATA";

export const UPGRADE_PLAN = "UPGRADE_PLAN";
export const UPGRADE_PLAN_RESPONSE = "UPGRADE_PLAN_RESPONSE";

export const INSERT_DATA = "INSERT_DATA";
export const INSERT_DATA_RESPONSE = "INSERT_DATA_RESPONSE";

export const REQ_LOAD_REG_USER_DATA = "REQ_LOAD_REG_USER_DATA";
export const REC_LOAD_REG_USER_DATA = "REC_LOAD_REG_USER_DATA";

export const REQUEST_ALL_RATE = "REQUEST_ALL_RATE";
export const ALL_RATE_RESPONSE = "ALL_RATE_RESPONSE";

export const ADD_RATE = "ADD_RATE";
export const ADD_RATE_RESPONSE = "ADD_RATE_RESPONSE";

export const REQUEST_ALL_DISCOUNT = "REQUEST_ALL_DISCOUNT";
export const ALL_DISCOUNT_RESPONSE = "ALL_DISCOUNT_RESPONSE";

export const ADD_DISCOUNT = "ADD_DISCOUNT";
export const ADD_DISCOUNT_RESPONSE = "ADD_DISCOUNT_RESPONSE";
export const REQUEST_ALL_PRICE_LIST = "REQUEST_ALL_PRICE_LIST";
export const ALL_PRICE_RESPONSE_LIST = "ALL_PRICE_RESPONSE_LIST";
export const ADD_PRICE = "ADD_PRICE";
export const ADD_PRICE_RESPONSE = "ADD_PRICE_RESPONSE";
export const REQUEST_LOAD_CHOOSEPLANS_LIST_EXTEND =
  "REQUEST_LOAD_CHOOSEPLANS_LIST_EXTEND";
export const RECEIVE_LOAD_CHOOSEPLANS_LIST_EXTEND =
  "RECEIVE_LOAD_CHOOSEPLANS_LIST_EXTEND";

export const CREATE_INVOICES_PAYMENT_TERMINATION_REQUEST =
  "CREATE_INVOICES_PAYMENT_TERMINATION_REQUEST";
export const CREATE_INVOICES_PAYMENT_TERMINATION_RESPONCES =
  "CREATE_INVOICES_PAYMENT_TERMINATION_RESPONCES";

export const PLAN_DETAILS_REQUEST = "PLAN_DETAILS_REQUEST";
export const PLAN_DETAILS_RESPONCES = "PLAN_DETAILS_RESPONCES";

export const YET_TO_INITIATE_DETAILS_REQUEST =
  "YET_TO_INITIATE_DETAILS_REQUEST";
export const YET_TO_INITIATE_DETAILS_RESPONCES =
  "YET_TO_INITIATE_DETAILS_RESPONCES";

export const ACCOUNT_NAME_REQUEST = "ACCOUNT_NAME_REQUEST";
export const ACCOUNT_NAME_RESPONCES = "ACCOUNT_NAME_RESPONCES";

export const SITE_NAME_REQUEST = "SITE_NAME_REQUEST";
export const SITE_NAME_RESPONCES = "SITE_NAME_RESPONCES";

export const REQUEST_TO_ACTIVATE_PLAN_BY_PROJECT_MANAGE =
  "REQUEST_TO_ACTIVATE_PLAN_BY_PROJECT_MANAGE";
export const RESPONCES_FOR_ACTIVATE_PLAN_BY_PROJECT_MANAGE =
  "RESPONCES_FOR_ACTIVATE_PLAN_BY_PROJECT_MANAGE";

export const REQUEST_PLAN_DETAILS = "REQUEST_PLAN_DETAILS";
export const RESPONCES_PLAN_DETAILS = "RESPONCES_PLAN_DETAILS";

export const REQUEST_INVOICE_URL = "REQUEST_INVOICE_URL";
export const RESPONSE_INVOICE_URL = "RESPONSE_INVOICE_URL";

export const REQUEST_CHECK_NOTICE_PERIOD = "REQUEST_CHECK_NOTICE_PERIOD";
export const RECEIVE_CHECK_NOTICE_PERIOD = "RECEIVE_CHECK_NOTICE_PERIOD";

export const UPDATE_NOTICE_PERIOD = "UPDATE_NOTICE_PERIOD";
export const UPDATE_NOTICE_PERIOD_RESPONSE = "UPDATE_NOTICE_PERIOD_RESPONSE";
export const REQUEST_ALL_NOTICE_PERIOD = "REQUEST_ALL_NOTICE_PERIOD";
export const ALL_NOTICE_PERIOD_RESPONSE = "ALL_NOTICE_PERIOD_RESPONSE";
export const DELETE_NOTICE_PERIOD = "DELETE_NOTICE_PERIOD";
export const DELETE_NOTICE_PERIOD_RESPONSE = "DELETE_NOTICE_PERIOD_RESPONSE";

export const ADD_NEWSLETTER = "ADD_NEWSLETTER";
export const ADD_NEWSLETTER_RESPONSE = "ADD_NEWSLETTER_RESPONSE";

// export const TIME_ZONE = 'TIME_ZONE';
// export const TIME_ZONE_RESPONSE ='TIME_ZONE_RESPONSE';
//-----------------Project Manager constants-----------
export const PROJECT_MANAGER_LOGIN_PAGE_RESPONSE =
  "PROJECT_MANAGER_LOGIN_PAGE_RESPONSE";
export const PROJECT_MANAGER_VERIFY_LOGIN = "PROJECT_MANAGER_VERIFY_LOGIN";

export const REQUEST_LOAD_PLAN_DETAILS = "REQUEST_LOAD_PLAN_DETAILS";
export const RECEIVE_LOAD_PLAN_DETAILS = "RECEIVE_LOAD_PLAN_DETAILS";

export const REQUEST_LOAD_ADMIN_PLAN_DETAILS = "REQUEST_LOAD_ADMIN_PLAN_DETAILS";
export const RECEIVE_LOAD_ADMIN_PLAN_DETAILS = "RECEIVE_LOAD_ADMIN_PLAN_DETAILS";

export const REQUEST_LOAD_DATE_CHANGE_PLAN_DETAILS = "REQUEST_LOAD_DATE_CHANGE_PLAN_DETAILS";
export const RECEIVE_LOAD_DATE_CHANGE_PLAN_DETAILS = "RECEIVE_LOAD_DATE_CHANGE_PLAN_DETAILS";


export const REQUEST_VARIABLE_PRICE = "REQUEST_VARIABLE_PRICE";
export const RESPONCES_VARIABLE_PRICE = "RESPONCES_VARIABLE_PRICE";
export const REQUEST_INQUIRY_LIST = "REQUEST_INQUIRY_LIST";
export const RECEIVE_INQUIRY_LIST = "RECEIVE_INQUIRY_LIST";
export const REQUEST_DYNAMIC_PRICE_FOR_PLAN = "REQUEST_DYNAMIC_PRICE_FOR_PLAN";

export const REQUEST_PLAN_PRICE_RESPONSE = "REQUEST_PLAN_PRICE_RESPONSE"

//------------>Partner Login-----------
export const VERIFY_PARTNER_LOGIN = "VERIFY_PARTNER_LOGIN";
export const PARTNER_LOGIN_PAGE_RESPONSE = "PARTNER_LOGIN_PAGE_RESPONSE";
export const PARTNER_VERIFY_OTP_LOGIN = "PARTNER_VERIFY_OTP_LOGIN";
export const PARTNER_RESPONCES_OTP_LOGIN = "PARTNER_RESPONCES_OTP_LOGIN ";
export const PARTNER_LOGIN_RESEND_OTP_VERIFY =
  "PARTNER_LOGIN_RESEND_OTP_VERIFY";
export const PARTNER_LOGIN_RESEND_OTP_RESPONSE =
  "PARTNER_LOGIN_RESEND_OTP_RESPONSE";
export const PARTNER_RECEIVE_LOAD_DISTRICT_DATA =
  "PARTNER_RECEIVE_LOAD_DISTRICT_DATA";

//------->onBoarding Engineer-------
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const ADD_EMPLOYEE_RESPONSE = "ADD_EMPLOYEE_RESPONSE";

// --------------requested Company--------
export const REQUESTED_PARTNERS = "REQUESTED_PARTNERS";
export const REQUESTED_PARTNERS_RESPONSE = "REQUESTED_PARTNERS_RESPONSE";
export const ACCEPT_COMPANY = "ACCEPT_COMPANY";
export const ACCEPT_COMPANY_RESPONSE = "ACCEPT_COMPANY_RESPONSE";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const DELETE_COMPANY_RESPONSE = "DELETE_COMPANY_RESPONSE";

// ----------- acceptedPartners-----------------
export const ACCEPTED_PARTNERS = "ACCEPTED_PARTNERS";
export const ACCEPTED_PARTNERS_RESPONSE = "ACCEPTED_PARTNERS_RESPONSE";

//------------------Accepted Self Employee----------------
export const ACCEPTED_SELF_EMPLOYEE = "ACCEPTED_SELF_EMPLOYEE";
export const ACCEPTED_SELF_EMPLOYEE_RESPONSE =
  "ACCEPTED_SELF_EMPLOYEE_RESPONSE";
// -----------------requestedSelfEmployee-------------------
export const REQUESTED_SELF_EMPLOYEE = "REQUESTED_SELF_EMPLOYEE";
export const REQUESTED_SELF_EMPLOYEE_RESPONSE =
  "REQUESTED_SELF_EMPLOYEE_RESPONSE";
export const ACCEPT_EMP = "ACCEPT_EMP";
export const ACCEPT_EMP_RESPONSE = "ACCEPT_EMP_RESPONSE";
export const DELETE_EMP = "DELETE_EMP";
export const DELETE_EMP_RESPONSE = "DELETE_EMP_RESPONSE";

//---------------Partner Registration-----------------------
export const SUBMIT_PARTNER = "SUBMIT_PARTNER";
export const SUBMIT_PARTNER_RESPONSE = "SUBMIT_PARTNER_RESPONSE";

//---------------SELFEMP Registration-----------------------
export const SUBMIT_SELFEMP = "SUBMIT_SELFEMP";
export const SUBMIT_SELFEMP_RESPONSE = "SUBMIT_SELFEMP_RESPONSE";
export const VERIFY_AADHAR = "VERIFY_AADHAR";
export const VERIFY_AADHAR_RESPONSE = "VERIFY_AADHAR_RESPONSE";

//--------------PARTNER RESET PASSWORD-------------------------
export const PARTNER_FORGOTPASSWORD_DATA = "PARTNER_FORGOTPASSWORD_DATA";
export const PARTNER_RECEIVE_FORGOTPASSWORD = "PARTNER_RECEIVE_FORGOTPASSWORD";
export const PARTNER_FORGOTPASSWORD_RESPONSE =
  "PARTNER_FORGOTPASSWORD_RESPONSE";

export const PARTNER_FORGOTPASSWORD_VERIFY_OTP =
  "PARTNER_FORGOTPASSWORD_VERIFY_OTP";
export const PARTNER_FORGOTPASSWORD_VERIFY_OTP_RESPONSE =
  "PARTNER_FORGOTPASSWORD_VERIFY_OTP_RESPONSE";
export const PARTNER_RESENDOTP_VERIFY = "PARTNER_RESENDOTP_VERIFY";
export const PARTNER_RESENDOTP_RESPONSE = "PARTNER_RESENDOTP_RESPONSE";
export const PARTNER_NEWPASSWORD_VERIFY = "PARTNER_NEWPASSWORD_VERIFY";
export const PARTNER_NEWPASSWORD_RESPONSE = "PARTNER_NEWPASSWORD_RESPONSE";

//--------------------SET NEW PASSWORD COMPANY SIDE-------------------
export const SNP_EMAIL_DATA = "SNP_EMAIL_DATA";
export const SNP_EMAIL_DATA_RESPONSE = "SNP_EMAIL_DATA_RESPONSE";
export const SNP_VERIFY_OTP = "SNP_VERIFY_OTP";
export const SNP_VERIFY_OTP_RESPONSE = "SNP_VERIFY_OTP_RESPONSE";
export const SNP_VERIFY_RESENDOTP = "SNP_VERIFY_RESENDOTP";
export const SNP_VERIFY_RESENDOTP_RESPONSE = "SNP_VERIFY_RESENDOTP_RESPONSE";
export const SNP_VERIFY_NEWPASSWORD = "SNP_VERIFY_NEWPASSWORD";
export const SNP_VERIFY_NEWPASSWORD_RESPONSE ="SNP_VERIFY_NEWPASSWORD_RESPONSE";
export const SNP_EMAIL_RECEIVE = "SNP_EMAIL_RECEIVE";
//------------------partners------------
export const ALL_PARTNERS_TICKETS_RESPONSE = "ALL_PARTNERS_TICKETS_RESPONSE";
export const REQUEST_ALL_PARTNERS_TICKETS = "REQUEST_ALL_PARTNERS_TICKETS";
export const REQUEST_ALL_SRN_REPORTS="REQUEST_ALL_SRN_REPORTS";
export const ALL_SRN_DATA_RESPONSE = "ALL_SRN_DATA_RESPONSE";

export const API_URLS = {
  GUEST_LOGIN_URL: "/b1desk/preLogin/registeration",
  VERIFY_OTP_REGISTER_URL: "/b1desk/postLogin/validateEmailAndOTP",
  CUSTOMER_VERIFY_OTP_REGISTER_URL: "/b1desk/postLogin/validateEmailAndOTP",
  LOGIN_VERIFY_OTP_URL: "/b1desk/postLogin/validateOtpEnteredByEmployee",
  VERIFY_OTP_URL: "/b1desk/postLogin/validateOtpEnteredByEmployee",
  LIST_CITY_URL: "/b1desk/preLogin/getCitiesByCountry",
  GUEST_RESENDOTP_REGISTER_URL: "/b1desk/preLogin/resendOtpToCustomer",
  REGISTER_PASSWORD_URL: "/b1desk/preLogin/insertRegisteredCustomerDetail",
  CUSTOMER_LOGIN_VERIFY_URL: "/b1desk/user/signIn",
  FORGOTPASSWORD_CUSTOMER_URL: "/b1desk/postLogin/verifyEmailAddress",
  VERIFY_CUSTOMER_OTP_URL: "/b1desk/postLogin/validateEmailAndOTP",
  LOGIN_RESENDOTP_CUSTOMER_URL: "/b1desk/postLogin/resendOtp",
  RESETPASSWORD_CUSTOMER_URL: "/b1desk/postLogin/resetPassword",

  // LOAD_USER_URL: '/user',
  //VERIFY_OTP_URL:'/b1desk/postLogin/validateOtpEnteredByEmployee',
  SALES_LOGIN_VERIFY_URL: "/b1desk/signInBySalesAdmin",
  ADD_USER_URL: "/b1desk/postLogin/createUser",
  LIST_TIMEZONE_URL: "/b1desk/getAllTimezones",
  LIST_TIMESLOT_URL: "/b1desk/postLogin/availableTimeSlots",
  REQUEST_DEMO_URL: "/b1desk/user/postLogin/demoRequest",
  LOGIN_VERIFY_URL: "/b1desk/signInByAdmin",
  LOAD_REQUEST_URL: "/b1desk/postLogin/listDemoRequests",
  LIST_USER_URL: "/b1desk/postLogin/listUsers",
  FORGOTPASSWORD_URL: "/b1desk/postLogin/verifyEmailAddressOfEmployee",
  RESETPASSWORD_URL: "/b1desk/postLogin/resetPasswordForEmployee",

  /* These are user requests URLs */
  LIST_SALESPERSON_URL: "/b1desk/postLogin/getAssigneesList",
  REQ_SAVE_ASSIGN_REQUEST_URL: "/b1desk/postLogin/assignSupport",
  REQ_SAVE_REASSIGN_REQUEST_URL: "/b1desk/postLogin/reassignSupport",
  REQ_AVAILABLE_SLOTS_URL: "/b1desk/postLogin/availableTimeSlots",
  REQ_SAVE_RESCHEDULE_REQUEST_URL: "/b1desk/postLogin/rescheduleRequest",
  REQ_CANCELLATION_REQUEST_URL: "/b1desk/postLogin/cancelRequest",
  REQ_COMPLETION_REQUEST_URL: "/b1desk/postLogin/completeRequest",
  ADD_FEEDBACK_URL: "/b1desk/postLogin/feedback",
  DETAIL_URL: "/b1desk/postLogin/getDemoDetailsByDemoId/",

  /*These are user manamgement URLs */
  DELETE_USER_URL: "/b1desk/postLogin/Xel3n1C3mp_RX",
  UPDATE_USER_URL: "/b1desk/postLogin/updateUserProfile",
  /*These are showroom manamgement URLs */
  FORGOTPASSWORD_VERIFY_OTP_URL:
    "/b1desk/postLogin/validateOtpEnteredByEmployee",
  LOGIN_RESENDOTP_URL: "/b1desk/postLogin/resendOtpForEmployee",
  LOGIN_RESEND_OTP_URL: "/b1desk/postLogin/resendOtpForEmployee",
  LIST_REPORTS_URL: "/b1desk/postLogin/getDemoDetailReports",
  REQ_CLEAR_TOKENS_URL: "/b1desk/logoutByAdmin",
  LIST_COMPANY_URL: "/b1desk/preLogin/getRegisteredCompany/",
  LIST_COMPANIES_URL: "/b1desk/postLogin/displayAllCompany",

  LIST_SERVICES_TAX_URL: "/b1desk/postLogin/getServiceTaxList",
  UPDATE_TAXS_URL: "/b1desk/postLogin/updateCountryTax",
  DELETE_TAXS_URL: "/b1desk/postLogin/deleteCountryTax",
  ADD_TAXS_URL: "/b1desk/postLogin/insertServiceTaxDetails",

  LITE_CALCULATE_PRICE_URL: "/b1desk/preLogin/calculatePrice",
  LITE_TIME_SLOT_URL: "/b1desk/preLogin/getTimeSlotForSupportWindow",
  LIST_UPDATE_USER_URL: "/b1desk/user/postLogin/displayCustomerProfile/",
  //LIST_EDIT_UPDATE_USER_URL:'/b1desk/postLogin/updateCustomerProfile',
  LITE_CALCULATE_PRICE_URL: "/b1desk/preLogin/calculatePrice",
  ENTERPRISE_CALCULATE_PRICE_URL: "/b1desk/preLogin/calculatePrice",
  PREMIUM_CALCULATE_PRICE_URL: "/b1desk/preLogin/calculatePrice",
  REQ_CLEAR_TOKENS_CUSTOMER_URL: "/b1desk/logoutByCustomer",
  CALCULATE_PRICE_URL: "/b1desk/preLogin/calculatePrice",
  GET_PRICE_DETAILS_URL: "/b1desk/preLogin/calculateEstimationValue",
  //PRICE_DETAILS_URL: "/b1desk/postLogin/updatedPlanOrderSummary",
  PRICE_DETAILS_URL:"/b1desk/user/postLogin/updatedPlanOrderSummaryNew",
  DMAS_AGREEMENT_URL: "/b1desk/user/postLogin/insertPlansDetails",
  INSERT_PLAN_URL: "/b1desk/user/postLogin/insertPlansDetails",
  GET_PRICE_BY_TERMS_URL: "/b1desk/preLogin/calculateEstimationValue",
  CURRENCY_INR_URL: "/b1desk/postLogin/getCurrencyRate",
  FILE_UPLOAD_URL: "/b1desk/user/uploadFilesToDB",
  CUSTOMERID_URL: "/b1desk/user/postLogin/listOfPlans/",
  VIEW_INVOICE_LIST_URL: "/b1desk/user/postLogin/listInvoices/",
  DMAS_ANNEXURE_URL: "/b1desk/postLogin/viewDmsa/",
  CHOOSEPLANS_URL: "/b1desk/user/postLogin/chosenPlans/",
  //CHOOSEPLANS_URL:'/b1desk/postLogin/chosenPlansForExtendContractDuration/',

  DOWNLOAD_URL:"https://books.zoho.in/api/v3/invoices/464704000000046002?organization_id=60006964262&accept=pdf",
  DETAIL_INVOICE_URL: "/b1desk/postLogin/getAllDetailsOfGivenInvoiceNumber/",
  INVOICE_NUMBER_URL: "/b1desk/preLogin/generateRandomWaiveOffCode",
  VALIDATE_INVOICE_NUMBER_URL: "/b1desk/preLogin/validateWaiveOff",
  RESEND_WAIVEOFF_CODE_URL: "/b1desk/preLogin/resendWaiveOffCode",
  CONTACT_US_URL: "/b1desk/postLogin/newContactMessage",
  LIST_CONTRACT_UPDATE_URL: "/b1desk/user/postLogin/extendContractDuration",
  LIST_CONTRACT_TERMINATE_URL: "/b1desk/user/postLogin/terminateService",
  DELETE_INVOICE_URL: "/b1desk/postLogin/deleteCreatedInvoice",
  CREATE_INVOICES_PAYMENT_URL: "/b1desk/user/postLogin/checksPaymentAuthentication",
  TAX_INVOICES_PAYMENT_URL: "/b1desk/postLogin/paymentAuthenticationForInvoice",
  CUSTOMIZE_LIST_TIMEZONE_URL: "/b1desk/getAllTimezones",
  LITE_AUTOMATED_TIME_URL: "/b1desk/preLogin/getAutomatedEndTimeSlot",
  LITE_AUTOMATED_TIME_ENTERPRISE_URL:
    "/b1desk/preLogin/getAutomatedEndTimeSlot",
  LITE_AUTOMATED_TIME_PREMIUM_URL: "/b1desk/preLogin/getAutomatedEndTimeSlot",
  LIST_EDIT_UPDATE_USER_URL: "/b1desk/postLogin/verifyEmailAddress",
  EDIT_PROFILE_UPDATE_URL: "/b1desk/user/postLogin/updateCustomerProfile",
  EDIT_RESEND_OTP_URL: "/b1desk/postLogin/resendOtp",
  CREATE_ORDER_ID: "/b1desk/user/postLogin/createOrder",
  LIST_DETAIL_URL: "/b1desk/user/postLogin/activePlans/",
  UPGRADE_PLAN_URL: "/b1desk/user/postLogin/checksUpgradeOrDegrade",
  INSERT_DATA_URL: "/b1desk/postLogin/insertUpdatedPlan",
  LOAD_REG_USER_URL: "/b1desk/postLogin/getAllRegisteredCustomers",
  LIST_EXCHANGE_RATE_URL: "/b1desk/postLogin/listOfCurrenciesExchangeRate",
  ADD_RATE_URL: "/b1desk/postLogin/updateExchangeRateValue",
  LIST_DISCOUNT_URL: "/b1desk/postLogin/listOfSubcriptionDiscountAmount",
  UPDATE_DISCOUNT_URL: "/b1desk/postLogin/updateDiscountForSubscription",
  LIST_PRICE_URL: "/b1desk/postLogin/listOfPlansPrice",
  UPDATE_PRICE_URL: "/b1desk/postLogin/updatePlanPrice",
  CHOOSEPLANS_EXTEND_URL:
    "/b1desk/user/postLogin/chosenPlansForExtendContractDuration/", 
  CREATE_INVOICES_PAYMENT_TERMINATION_URL:
    "/b1desk/postLogin/paymentAuthenticationForTermination",
  CREATE_ORDER_ID_TERMINATION_URL: "/b1desk/user/postLogin/createOrder",
  PLAN_DETAILS_REQUEST_URL: "/b1desk/postLogin/getAllPlansDetails",
  PLANDETAILS_URL: "/b1desk/user/postLogin/getPlanDetails/",
  INVOICE_URL: "/b1desk/user/postLogin/PdfFileDownload/",
  INVOICES_PAYMENT_URL: "/b1desk/postLogin/paymentAuthenticationForInvoice",

  //INVOICE_URL:'/b1desk/postLogin/getAllDetailsOfGivenInvoiceNumber/',
  NOTICE_PERIOD_URL: "/b1desk/user/postLogin/checkPlanExpirationForNoticePeriod",

  LIST_NOTICE_PERIOD_URL: "/b1desk/postLogin/getNoticePeriod",
  UPDATE_NOTICE_PERIOD_URL: "/b1desk/postLogin/updateNoticePeriod",
  DELETE_NOTICE_PERIOD_URL: "/b1desk/postLogin/deleteNoticePeriod",
  ADD_NOTICE_PERIOD_URL: "/b1desk/postLogin/insertNoticePeriod",
  ADD_NEWSLETTER_URL: "/b1desk/postLogin/NewsLetter",
  UPGRADE_AND_DOWNGRADE_CHECK: "/b1desk/user/postLogin/checksUpgradeOrDegrade",
  UPGRADE_AND_DOWNGRADE_ORDER_SUMMERY: "/b1desk/user/postLogin/updatedPlanOrderSummaryNew",
  TIME_ZONE_URL: "/b1desk/postLogin/timeZone",
  //-----------prokect Manager URL-----------
  PROJECT_MANAGER_LOGIN_VERIFY_URL: "/b1desk/signInByProjectManager",
  YET_TO_INITIATE_DETAILS_REQUEST_URL:
    "/b1desk/postLogin/getAllInitiatedCustomizePlans",
  ACCOUNT_NAME_REQUEST_URL: "/b1desk/postLogin/getAllAccounts",
  SITE_NAME_REQUEST_URL: "/b1desk/postLogin/getAllSitesByAccount/",
  PROJECT_MANAGER_ACTIVATE_PLAN_REQUEST_URL:
    "/b1desk/postLogin/activatePlanByProjectManager",
    LOAD_PLAN_DETAILS:'/b1desk/user/postLogin/getAllActiveCustomerDetail/',
    LOAD_ADMIN_PLAN_DETAILS:'/b1desk/postLogin/statusForAllPlans',
    LOAD_DATE_CHANGE_PLAN_DETAILS:'/b1desk/postLogin/getTicketsByDateAndCustomerId/',
    VARIABLE_PRICE_CHNAGE:'/b1desk/postLogin/updateVariableCost',
    REQUEST_ALL_CLIENTS_URL:'/b1desk/AcceptOrDenyNewAdmin',
    DELETE_CLIENT_URL:'/b1desk/postLogin/DenyAdminAccess',
    ADD_CLIENT_URL:'/b1desk/postLogin/AcceptAsAdminForOrganization',
    REQUEST_ALL_PRICE_LIST_URL:'/b1desk/postLogin/listOfPlansPriceForHomePage',
    REQUEST_INQUIRY_LIST_URL: "/b1desk/preLogin/FAQrequest",
    REQUEST_DYNAMIC_PRICE_FOR_PLAN: '/b1desk/preLogin/calculateDynamicPriceOnPricingPlans',
    REQUEST_COMPANY_ID:'/b1desk/getTaxByCompany',
  //partner login url
 
  PARTNER_LOGIN_VERIFY_URL: "/b1desk/newPartnerLogin",
  PARTNER_LOGIN_VERIFY_OTP_URL:
    "/b1desk/postLogin/validateEmailAndOtpOfPartner",
  LOGIN_RESEND_OTP_URL_PARTNER: "/b1desk/preLogin/resendOtpToPartner",

  //----company - req and accept-------

  REQUESTED_PARTNERS_URL: "/b1desk/postLogin/getCompanyPartnersAndRequests",
  ACCEPTED_PARTNERS_URL: "/b1desk/postLogin/getCompanyPartnersAndRequests",
  ACCEPT_COMPANY_URL: "/b1desk/postLogin/AcceptOrDenyCompany",

  //-----self_emp-req and accept----------
  REQUESTED_SELF_EMPLOYEE_URL: "/b1desk/postLogin/getAllSelfEmployeePartners",
  ACCEPTED_SELF_EMPLOYEE_URL: "/b1desk/postLogin/getAllSelfEmployeePartners",
  ACCEPT_EMP_URL: "/b1desk/postLogin/AcceptOrDenyEmployeeRequest",

  //------Partner Registration---------
  SUBMIT_PARTNER_URL: "/b1desk/preLogin/PartnerSignUp",

  //--------self emp registration----
  SUBMIT_SELFEMP_URL: "/b1desk/preLogin/SelfEmployeeSignUp",
  VERIFY_AADHAR_URL: "/b1desk/postLogin/aadharVerification/",

  //---------- partner forgetten password--------
  PARTNER_FORGOTPASSWORD_URL: "/b1desk/postLogin/verifyEmailAddressOfPartner",
  PARTNER_VERIFY_OTP_URL: "/b1desk/postLogin/validateEmailAndOtpOfPartner",
  PARTNER_RESENDOTP_URL: "/b1desk/preLogin/resendOtpToPartner",
  PARTNER_NEWPASSWORD_URL: "/b1desk/postLogin/resetPasswordForPartner",

  //-------------------set New Password ------------------------
  SNP_VERIFY_EMAIL_URL: "/b1desk/postLogin/verifyEmailAddressOfPartner",
  SNP_VERIFY_OTP_URL: "/b1desk/postLogin/validateEmailAndOtpOfPartner",
  SNP_RESENDOTP_URL: "/b1desk/preLogin/resendOtpToPartner",
  SNP_NEWPASSWORD_URL: "/b1desk/postLogin/resetPasswordForPartner",

};
