import * as Constants from "../constants";
export const addUser = (
  employeeId,
  partnerId,
  firstName,
  lastName,
  gender,
  email,
  mobile,
  mobileCountryCode,
  qualification,
  specialization,
  experience,
  country,
  address,
  city,
  stateName,
  pincode,
  idProof,
  addressProof,
  panCard,
  aadharCard
) => ({
  type: Constants.ADD_EMPLOYEE,
  url: Constants.API_URLS.ADD_EMPLOYEE_URL,
  employeeId,
  partnerId,
  firstName,
  lastName,
  gender,
  email,
  mobile,
  mobileCountryCode,
  qualification,
  specialization,
  experience,
  country,
  address,
  city,
  stateName,
  pincode,
  idProof,
  addressProof,
  panCard,
  aadharCard,
});

export const addUserResponse = (isDetailSuccess) => ({
  type: Constants.ADD_EMPLOYEE_RESPONSE,
  isDetailSuccess,
});
